import { fileURLToPath } from 'node:url';

export * as schema from './schema.js';
export * from './schema.js';
// Query helpers, re-exported so every workspace uses this package's drizzle-orm instance.
export { and, eq, gt, inArray, isNull, lt, or, sql } from 'drizzle-orm';
export { createDatabase, type Database, type DatabaseConnection } from './database.js';
export {
  TOO_FAST_REVIEW,
  tooFastAccounts,
  type TooFastAccount,
  type TooFastOptions,
} from './too-fast.js';

/** SQL migrations generated by drizzle-kit (`pnpm db:generate`), shipped with the package. */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL('../drizzle', import.meta.url));
