import { fileURLToPath } from 'node:url';

export * as schema from './schema.js';
export * from './schema.js';

/** SQL migrations generated by drizzle-kit (`pnpm db:generate`), shipped with the package. */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL('../drizzle', import.meta.url));
